### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by vthorsteinsson** [sverrirab/icenews#1]
I would like to point out that although Icenews is licensed under Apache, it depends on Reynir which is licensed under GPLv3. Differing from Apache, GPLv3 does not permit closed redistribution. If you want to redistribute Reynir in a closed manner, please contact the copyright owner, Miðeind ehf. (see https://github.com/mideind), to negotiate the terms of such a license.

**Comment by sverrirab** [comment]
There is a note on this here to make this clear to users: https://github.com/sverrirab/icenews/blob/master/README.md#note-on-licensing that is displayed prominently on the front page.  All distribution of icenews is open so any users installing this package (e.g. using pip or docker) and are using it as a standalone service are conforming to all of the licenses mentioned in the note.
